apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-db
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
      - name: myapp-db
        image: patrickmlima/k8s-lab1-database:v1
        imagePullPolicy: Always
        args:
          - "--ignore-db-dir"
          - "lost+found"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent
        persistentVolumeClaim:
          claimName: db-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: myapp-backend
        image: patrickmlima/k8s-lab1-backend:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
